- name: mkdir {{ ansible_env.HOME }}/local
  file:
    path: '{{ ansible_env.HOME }}/local'
    state: directory
    mode: 0755

- name: unzip go 1.12.7
  unarchive:
    src: https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
    dest: '{{ ansible_env.HOME }}/local'
    remote_src: yes