- name: unzip ghq 0.12.6
  unarchive:
    src: https://github.com/motemen/ghq/releases/download/v0.12.6/ghq_linux_amd64.zip
    dest: '{{ ansible_env.HOME }}/local'
    remote_src: yes

- name: symbolic link ghq
  file:
    src: '{{ ansible_env.HOME }}/local/ghq_linux_amd64/ghq'
    dest: '{{ ansible_env.HOME }}/bin/ghq'
    state: link